name: MD to PDF with Pandoc

on:
  workflow_dispatch:
  push:
  pull_request:

env:
  MD_FILE: README.md
  OUTPUT_PDF: ${{ github.event.repository.name }}.pdf

jobs:
  build:
    runs-on: ubuntu-latest
    # https://stackoverflow.com/a/58142412/18479243
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Set up Ubuntu
        run: sudo apt-get update
  
      - name: Install dependencies
        run: >
          sudo apt-get install
          pandoc
          texlive-latex-base
          texlive-fonts-recommended
          texlive-fonts-extra
          texlive-latex-extra
        
      - name: MD to PDF with Pandoc
        run: pandoc ${{ env.MD_FILE }} -o ${{ env.OUTPUT_PDF }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: |
            ${{ env.OUTPUT_PDF }}
